# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AC-iOS-Final' do
  use_frameworks!

  pod 'Firebase'	
  pod 'Firebase/Auth'
  pod 'Firebase/Database’
  pod 'Firebase/Storage'
  pod ‘SnapKit’

end
